import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:todoApp/feature/daily_todos/models/daily_todo.dart';
import 'package:todoApp/feature/todos/models/todo.dart';

// This will be generated by build_runner
part 'daily_todo_isar.g.dart';

/// Isar model for DailyTodo
@collection
class DailyTodoIsar {
  // Isar ID - auto-incremented
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String dateId;

  late String dateIso;
  int taskGoal = 0;
  int completedTodosCount = 0;
  int deletedTodosCount = 0;

  // Store todo IDs for persistence - only field stored in Isar
  List<String> todoIds = [];

  // The actual todos list - transient, not stored in Isar
  @ignore
  List<Todo> todos = [];

  /// Summary text
  String? summary;

  /// Convert from domain model to Isar model
  static DailyTodoIsar fromDomain(DailyTodo dailyTodo) {
    // Extract just the IDs for storage
    final todoIdsList = dailyTodo.todos.map((todo) => todo.id).toList();

    final dailyTodoIsar = DailyTodoIsar()
      ..dateId = dailyTodo.id
      ..dateIso = dailyTodo.date.toIso8601String()
      ..taskGoal = dailyTodo.taskGoal
      ..completedTodosCount = dailyTodo.completedTodosCount
      ..deletedTodosCount = dailyTodo.deletedTodosCount
      ..todoIds = todoIdsList
      ..todos = dailyTodo.todos // Reference only, not stored
      ..summary = dailyTodo.summary;

    debugPrint(
        '📆 [DailyTodoIsar] Created from domain: ${dailyTodo.id}, goal: ${dailyTodo.taskGoal}, todos: ${dailyTodo.todos.length}');
    return dailyTodoIsar;
  }

  /// Convert to domain model
  DailyTodo toDomain() {
    final date = DateTime.parse(dateIso);

    return DailyTodo(
      id: dateId,
      date: date,
      taskGoal: taskGoal,
      completedTodosCount: completedTodosCount,
      deletedTodosCount: deletedTodosCount,
      todos: todos,
      summary: summary,
    );
  }
}
