import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';
import 'package:todoApp/feature/todos/models/daily_todos.dart';

// This will be generated by build_runner
part 'daily_todos_isar.g.dart';

/// Isar model for DailyTodo
@collection
class DailyTodosIsar {
  // Isar ID - auto-incremented
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String dateId;

  late String dateIso;
  int taskGoal = 0;
  int completedTodosCount = 0;
  int deletedTodosCount = 0;

  @ignore
  List<String> todoIds = [];

  /// Store the todo IDs as a comma-separated string for Isar
  String todoIdsString = '';

  /// Summary text
  String? summary;

  /// Convert from domain model to Isar model
  static DailyTodosIsar fromDomain(DailyTodos todoDate) {
    final todoDateIsar = DailyTodoIsar()
      ..dateId = todoDate.id
      ..dateIso = todoDate.date.toIso8601String()
      ..taskGoal = todoDate.taskGoal
      ..completedTodosCount = todoDate.completedTodosCount
      ..deletedTodosCount = todoDate.deletedTodosCount
      ..todoIds = todoDate.todoIds
      ..todoIdsString = todoDate.todoIds.join(',')
      ..summary = todoDate.summary;

    debugPrint(
        '📆 [DailyTodoIsar] Created from domain: ${todoDate.id}, goal: ${todoDate.taskGoal}');
    return todoDateIsar;
  }

  /// Convert to domain model
  DailyTodos toDomain() {
    final date = DateTime.parse(dateIso);

    // Convert todoIdsString to List<String>
    final List<String> todoIdsList =
        todoIdsString.isEmpty ? [] : todoIdsString.split(',');

    return DailyTodos(
      id: dateId,
      date: date,
      taskGoal: taskGoal,
      completedTodosCount: completedTodosCount,
      deletedTodosCount: deletedTodosCount,
      todoIds: todoIdsList,
      summary: summary,
    );
  }
}
